#!/bin/sh

#
# Rotate Logs - Keep 1 week's worth of data locally
#
# TODO DHM put this into a loop instead of a bunch of if statements

if [ -f '/opt/hethio/log/speedtest.log' ]; then

#remove last log
if [ -f '/opt/hethio/log/speedtest.7.log' ]; then
	rm -f /opt/hethio/log/speedtest.7.log
fi
if [ -f '/opt/hethio/log/speedtest.6.log' ]; then
	mv -f /opt/hethio/log/speedtest.6.log /opt/hethio/log/speedtest.7.log
fi
if [ -f '/opt/hethio/log/speedtest.5.log' ]; then
	mv -f /opt/hethio/log/speedtest.5.log /opt/hethio/log/speedtest.6.log
fi
if [ -f '/opt/hethio/log/speedtest.4.log' ]; then
	mv -f /opt/hethio/log/speedtest.4.log /opt/hethio/log/speedtest.5.log
fi
if [ -f '/opt/hethio/log/speedtest.3.log' ]; then
	mv -f /opt/hethio/log/speedtest.3.log /opt/hethio/log/speedtest.4.log
fi
if [ -f '/opt/hethio/log/speedtest.2.log' ]; then
	mv -f /opt/hethio/log/speedtest.2.log /opt/hethio/log/speedtest.3.log
fi
if [ -f '/opt/hethio/log/speedtest.1.log' ]; then
	mv -f /opt/hethio/log/speedtest.1.log /opt/hethio/log/speedtest.2.log
fi

mv -f /opt/hethio/log/speedtest.log /opt/hethio/log/speedtest.1.log

touch /opt/hethio/log/speedtest.log
chmod 775 /opt/hethio/log/speedtest.log
chgrp hethio /opt/hethio/log/speedtest.log

fi





if [ -f '/opt/hethio/log/publicip.log' ]; then

#remove last log
if [ -f '/opt/hethio/log/publicip.7.log' ]; then
	rm -f /opt/hethio/log/publicip.7.log
fi
if [ -f '/opt/hethio/log/publicip.6.log' ]; then
	mv -f /opt/hethio/log/publicip.6.log /opt/hethio/log/publicip.7.log
fi
if [ -f '/opt/hethio/log/publicip.5.log' ]; then
	mv -f /opt/hethio/log/publicip.5.log /opt/hethio/log/publicip.6.log
fi
if [ -f '/opt/hethio/log/publicip.4.log' ]; then
	mv -f /opt/hethio/log/publicip.4.log /opt/hethio/log/publicip.5.log
fi
if [ -f '/opt/hethio/log/publicip.3.log' ]; then
	mv -f /opt/hethio/log/publicip.3.log /opt/hethio/log/publicip.4.log
fi
if [ -f '/opt/hethio/log/publicip.2.log' ]; then
	mv -f /opt/hethio/log/publicip.2.log /opt/hethio/log/publicip.3.log
fi
if [ -f '/opt/hethio/log/publicip.1.log' ]; then
	mv -f /opt/hethio/log/publicip.1.log /opt/hethio/log/publicip.2.log
fi

mv -f /opt/hethio/log/publicip.log /opt/hethio/log/publicip.1.log

touch /opt/hethio/log/publicip.log
chmod 775 /opt/hethio/log/publicip.log
chgrp hethio /opt/hethio/log/publicip.log

fi