#!/bin/sh

#
# Rotate Logs - Keep 1 week's worth of data locally
#
# TODO DHM put this into a loop instead of a bunch of if statements

if [ -f '/opt/hethio/log/temperature.log' ]; then

#remove last log
if [ -f '/opt/hethio/log/temperature.7.log' ]; then
	rm -f /opt/hethio/log/temperature.7.log
fi
if [ -f '/opt/hethio/log/temperature.6.log' ]; then
	mv -f /opt/hethio/log/temperature.6.log /opt/hethio/log/temperature.7.log
fi
if [ -f '/opt/hethio/log/temperature.5.log' ]; then
	mv -f /opt/hethio/log/temperature.5.log /opt/hethio/log/temperature.6.log
fi
if [ -f '/opt/hethio/log/temperature.4.log' ]; then
	mv -f /opt/hethio/log/temperature.4.log /opt/hethio/log/temperature.5.log
fi
if [ -f '/opt/hethio/log/temperature.3.log' ]; then
	mv -f /opt/hethio/log/temperature.3.log /opt/hethio/log/temperature.4.log
fi
if [ -f '/opt/hethio/log/temperature.2.log' ]; then
	mv -f /opt/hethio/log/temperature.2.log /opt/hethio/log/temperature.3.log
fi
if [ -f '/opt/hethio/log/temperature.1.log' ]; then
	mv -f /opt/hethio/log/temperature.1.log /opt/hethio/log/temperature.2.log
fi

mv -f /opt/hethio/log/temperature.log /opt/hethio/log/temperature.1.log

touch /opt/hethio/log/temperature.log
chmod 775 /opt/hethio/log/temperature.log
chgrp hethio /opt/hethio/log/temperature.log

fi