#!/bin/sh
#
# HethIO Monthly Script
#

if [ -f "/etc/hethio/hethio.conf" ]; then
	MPATH=$(awk -F "=" '/PATH/ {print $2}' /etc/hethio/hethio.conf)

	cd $MPATH/bin

	if [ -f $MPATH/bin/temperature-log-rotator ]; then
		echo "Rotate Temperature Logs"
		$MPATH/bin/temperature-log-rotator
	fi

	if [ -f $MPATH/bin/speedtest-log-rotator ]; then
		echo "Rotate Speedtest Logs"
		$MPATH/bin/speedtest-log-rotator
	fi

	if [ -f $MPATH/bin/publicip-log-rotator ]; then
		echo "Rotate Public IP Logs"
		$MPATH/bin/publicip-log-rotator
	fi

	if [ -f /usr/bin/hethio-agent ]; then
		service hethio restart
	fi

fi
