#!/bin/sh
#
# Minion Hourly Script
#

if [ -f "/etc/openmqtt/openmqtt.conf" ]; then
	MPATH=$(awk -F "=" '/PATH/ {print $2}' /etc/openmqtt/openmqtt.conf)

	cd $MPATH/bin

	if [ -f $MPATH/bin/temperature ]; then
		echo "Log Current Temperature to running file"
		$MPATH/bin/temperature
	fi

	if [ -f $MPATH/bin/speedtest ]; then
		echo "Run Internet Speedtest every hour"
		$MPATH/bin/speedtest
	fi

	if [ -f $MPATH/bin/system-info ]; then
		echo "System Information"
		$MPATH/bin/system-info
	fi

fi
