#!/bin/sh

#
# Minion Monthly Script
#

echo "Rotate Temperature Logs"
/opt/minion/bin/temperature-log-rotator

echo "Rotate Speedtest Logs"
/opt/minion/bin/speedtest-log-rotator

echo "Rotate Public IP Logs"
/opt/minion/bin/publicip-log-rotator
