#!/bin/sh
#
# Minion Monthly Script
#

if [ -f "/etc/minion.conf" ]; then
	MPATH=$(awk -F "=" '/MPATH/ {print $2}' /etc/minion.conf)

	cd $MPATH/bin

	if [ -f $MPATH/bin/temperature-log-rotator ]; then
		echo "Rotate Temperature Logs"
		$MPATH/bin/temperature-log-rotator
	fi

	if [ -f $MPATH/bin/speedtest-log-rotator ]; then
		echo "Rotate Speedtest Logs"
		$MPATH/bin/speedtest-log-rotator
	fi

	if [ -f $MPATH/bin/publicip-log-rotator ]; then
		echo "Rotate Public IP Logs"
		$MPATH/bin/publicip-log-rotator
	fi

fi
