#!/bin/sh
#
# Minion Hourly Script
#

if [ -f "/etc/minion.conf" ]; then
	MPATH=$(awk -F "=" '/MPATH/ {print $2}' /etc/minion.conf)

	cd $MPATH/bin

	if [ -f $MPATH/bin/temperature ]; then
		echo "Log Current Temperature to running file"
		$MPATH/bin/temperature
	fi

	if [ -f $MPATH/bin/speedtest ]; then
		echo "Run Internet Speedtest every hour"
		$MPATH/bin/speedtest
	fi

	if [ -f $MPATH/bin/generalinfo ]; then
		echo "General Information"
		$MPATH/bin/generalinfo
	fi

fi
