#!/bin/sh
#
# This script typically modifies links or other files associated with foo, 
# and/or removes files created by the package.
#

# Delete config directory if it exists
if [ -d /etc/hethio ]; then
	rm -rf /etc/hethio
fi

# Remove hethio at startup
update-rc.d -f hethio-agent remove

# Remove Service Script
if [ -d /etc/init.d/hethio-agent ]; then
	rm -rf /etc/init.d/hethio-agent
fi

if [ -d /var/log/hethio ]; then
	rm -rf /var/log/hethio
fi