#!/bin/sh
#
# This script typically modifies links or other files associated with foo, 
# and/or removes files created by the package.
#

# Delete config directory if it exists
if [ -d /etc/hethio ]; then
	#don't remove directory if server is installed
	if [ !-f /etc/hethio/server.conf ]; then
		rm -rf /etc/hethio
	else
		rm /etc/hethio/agent.conf
	fi
fi

# Remove hethio at startup
update-rc.d -f hethio-agent remove

# Remove Service Script
if [ -f /etc/init.d/hethio-agent ]; then
	rm -rf /etc/init.d/hethio-agent
fi

if [ -d /var/log/hethio ]; then
	if [ !-f /var/log/hethio/server.log ]; then
		rm -rf /var/log/hethio
	else
		rm /var/log/hethio/agent*
	fi
fi