#!/bin/sh
#
# This script executes before that package will be unpacked from its Debian 
# archive (".deb") file. Many 'preinst' scripts stop services for packages 
# which are being upgraded until their installation or upgrade is completed 
# (following the successful execution of the 'postinst' script).
#
echo "<preinst>"

# Stop hethio-agent service if it exists
if [ -f /etc/init.d/hethio-agent ]; then
	echo "Stopping service."
	chmod +x /etc/init.d/hethio-agent
	/etc/init.d/hethio-agent stop
fi

