#!/bin/bash
#
# Test Internet Connection
#

source globals.sh

if [ -f "$MPATH/bin/speedtest-cli" ]; then
	echo "Testing internet speed..."

	$MPATH/bin/speedtest-cli > $MPATH/log/speedtest.lastrun.log

	TIMESTAMP=`date +"%s"`
	PUBLICIP=`cat $MPATH/log/speedtest.lastrun.log | grep 'Testing from' | awk -F'(' '{print $2}' | awk -F ')' '{print $1}'`
	RESULTS=`cat $MPATH/log/speedtest.lastrun.log | grep 'Mbits/s' | awk -F':' '{print $2}' | awk -F' ' '{print $1;}' | awk 'NR%2{printf $0"|";next;}1'`
	DOWNLOAD=`echo $RESULTS | awk -F'|' '{print $1}'`
	UPLOAD=`echo $RESULTS | awk -F'|' '{print $2}'`

	echo "Public IP Address:  $PUBLICIP"
	echo "$PUBLICIP|$DATETIME" >> $MPATH/log/publicip.log

	echo "Download Speed: $DOWNLOAD"
	echo "Upload Speed: $UPLOAD"
	echo "$DOWNLOAD|$UPLOAD|$DATETIME" >> $MPATH/log/speedtest.log  



	#- IP -  ip address information like public ip address, etc.
	if [ -f "$MPATH/log/publicip.log" ]; then
	PUBLICIP=`awk '/./{line=$0} END{print line}' $MPATH/log/publicip.log | cut -d'|' -f1`
	else
	PUBLICIP='UNKNOWN'
	fi
	IP="'ip':{'public':'$PUBLICIP'}"


	#- SPEED - run an internet speedtest every hour so we have a running log.
	if [ -f "$MPATH/log/speedtest.log" ]; then
	DOWNLOAD=`awk '/./{line=$0} END{print line}' $MPATH/log/speedtest.log | cut -d'|' -f1`
	UPLOAD=`awk '/./{line=$0} END{print line}' $MPATH/log/speedtest.log | cut -d'|' -f2`
	else
	DOWNLOAD='UNKNOWN'
	UPLOAD='UNKNOWN'
	fi
	SPEED="'speed':{'download':'$DOWNLOAD','upload':'$UPLOAD'}"


	publish "machines/$ID/internet" "{$IP,$SPEED}"



	echo "Done"
else
	echo "Unable to run speedtest, missing test utility."
fi
